### PR TITLE
HW

### PR DESCRIPTION
**Pull request by roiroi123**
HW

### CODE REVIEW

**Comment by roiroi123** [comment]
i did  the checkout on "adding_ip_list" branch , then i created my branch , did checkout again to my created branch and then made the changes , (did the add and commit ) but when i tried to push origin head i got a message "remote: Permission to galamo/gitLesson.git denied to roiroi123"

**Comment by roiroi123** [comment]
[gitLesson.zip](https://github.com/galamo/gitLesson/files/4786289/gitLesson.zip)

**Comment by roiroi123** [comment]
do i just needed to w8 for u to just give me permission ?

**Comment by roiroi123** [comment]
[gitLesson.zip](https://github.com/galamo/gitLesson/files/4786329/gitLesson.zip)

**Comment by roiroi123** [comment]
sorry a misunderstanding i thought i needed to add a branch to ur repo not mine -_-

**Comment by galamo** [comment]
Hi
missing pull request ni the repo

>

**Pull request closed without merging**
